### PR TITLE
Added Steam Group support, Added .idea dir to .gitignore

### PR DESCRIPTION
**Pull request by crock**
Steam Group support is confirmed to be reliable as I implement it this way in my own [checker](https://github.com/checker/cli).

Also, I added the configuration directory for all of JetBrain's IDEs to the .gitignore

### CODE REVIEW

**Comment by crock** [comment]
Done.

**Comment by crock** [comment]
@hoadlck I think it failed this time for no fault of my commit. The test suite appears to be not using the username I provided in the dictionary to test with.

**Comment by crock** [comment]
All the tests pass when run locally.

**Comment by hoadlck** [comment]
Thanks, the development looks good.  I looked at the test failure, and it is the iMGSRC.RU site having a failure to connect. I have had this happen to me too: the site does not seem to be reliable.

**Pull request merged**
