### PR TITLE
[Alternative] - Solve issue 5 with Colorama.

### PR DESCRIPTION
**Pull request by jcs090218**
Fixed issue #5, using `Colorama`. Notice there is another PR using `Hue` here => #62 to resolve the same issue. I think both of them work well on Windows 10 with `PowerShell` and `Command Prompt`. I have tested both softwares but I have not tested on the Linux machine. Since `Colorama` is well known as cross OS and my PC crashed yesterday while installing Python 3.7 (Damn it!), I would not worry too much about it but if anyone would like to tested on their Linux distros and MacOS are welcome.

### CODE REVIEW

**Comment by TheYahya** [comment]
Tnx @jcs090218 , It worked good on MacOS and Linux. I thinks this would be the solution.

@nareddyt, Can you try it on windows and review this PR?

**Comment by jcs090218** [comment]
@TheYahya No problem! I am concerned about the readability https://github.com/TheYahya/sherlock/issues/5#issuecomment-451051326 and OS compatibility, I did some research and made a simple list of two color libraries' comparison below.
#### Hue ####
* Works on `Windows 10`/`Linux`/`MacOS`. (Lose)
* Supports bright colors. (Win)
#### Colorama ####
* Works on `Windows`/`Linux`/`MacOS`. (Win)
* No supports bright colors. (Lost)

I personally reckon and prefer `Colorama`'s style more than `Hue`'s style https://github.com/TheYahya/sherlock/issues/5#issuecomment-451051326, and beyond that, OS compatibility is way more important than weather the `bright colors` is supported or not, in my opinion. As the matter of fact, both of the color libraries are working on their defects. `Colorama` has the advantage at the moment but maybe it would not be sooner. Hope these information would help!

**Comment by nareddyt** [comment]
Works great on Windows Command Line!

@TheYahya Code looks good and is ready to merge. Unfortunately, I do not have permission to add a review on the PR. You would have to add me as a _collaborator_ in the settings for this repo. Feel free to add me if you'd like, no worries otherwise :)

For documentation purposes, here's the output on Windows Command Line with this change.

## Before

image

## With this PR

image

**Comment by TheYahya** [comment]
Tnx @jcs090218 😊 
And thank you @nareddyt, I add you to collaborators too. you have full access to the repo now, so use it ☺️

**Comment by nareddyt** [comment]
> Tnx @jcs090218 😊
> And thank you @nareddyt, I add you to collaborators too. you have full access to the repo now, so use it ☺️

Let me know if there's any specific issues / PRs you need help with! As I mentioned to @sdushantha, I don't have much time to dedicate to this project, but I'm certainly willing to help! Also feel free to point any new contributors asking for help with git/github to me, I can walk them through the process 👍

**Comment by hoadlck** [comment]
After this update, the coloring no longer works in my Git Bash shell.  I am using Windows 10 with Git For Windows 2.17.0.windows.1 (https://gitforwindows.org/).

It does work fine in my Git CMD window, or a regular Windows command shell.  This is odd, as before the update the coloring **only** worked in the Git Bash shell, and acted weird in the other shells.

Personally, I was never a fan of the colors.  But I know that there are people that like this feature, so I am mentioning it.

shells

**Comment by jcs090218** [comment]
@hoadlck Thank you for reporting this, I will look into it and see if this could be resolved. I am really confused at the moment, and not quite sure there are other alternatives could get around this issue...

**Pull request merged**
